apiVersion: apps/v1
kind: Deployment
metadata:
  name: bahnhof-l
  labels:
    app: bahnhof-l
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bahnhof-l
  template:
    metadata:
      labels:
        app: bahnhof-l
    spec:
      containers:
      - name: bahnhof-l
        image: crisfromaustria/bahnhof
        ports:
        - containerPort: 8080
        env:
        - name: bahnhof
          value: Linz
        - name: bahnhofList
          value: Wien,Salzburg
---
apiVersion: v1
kind: Service
metadata:
  name: bahnhof-linz
spec:
  type: LoadBalancer
  selector:
    app: bahnhof-l
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
