version: 0.2

phases: 
    install:
        commands:
            - echo "install phase"
            - java -version
            - mvn --version
        finally:
            - echo "install phase finally"
    pre_build:
        commands: 
            - echo "pre_build phase"
        finally:
            - echo "pre_build finally"
    build:
        commands:
            - echo "build phase BEG"
            - mvn clean package
            - echo "build phase END"
        finally:
            - echo "build finally"
    post_build:
        commands:
            - echo "post_build phase"
            - cp target/bahnhof.jar .
            - ls -la
            - pwd
            - ls -la target
        finally:
            - echo "post_build finally"
artifacts:
    files:
        - "**/*"
