version: 0.2

phases: 
    install:
        runtime-versions:
            java: corretto17
        commands:
            - echo "install phase"
            - java -version
            - mvn --version
        finally:
            - echo "install finally"
    pre_build:
        commands: 
            - echo "pre_build phase"
        finally:
            - echo "pre_build finally"
    build:
        commands:
            - echo "build phase"
            - mvn clean package
        finally:
            - echo "build finally"
    post_build:
        commands:
            - echo "post_build phase"
            - ls -la
            - pwd
            - ls -la target
        finally:
            - echo "post_build finally"
artifacts:
    files:
        - "**/*"
