version: 0.2

phases: 
    install:
        runtime-versions:
            java: corretto17
        commands:
            - echo "install phase"
        finally:
            - echo "install finally"
    pre_build:
        commands: 
            - echo "pre_build phase"
    build:
        commands:
            - echo "build phase"
    post_build:
        commands:
            - echo post_build phase"
